build:
 image: maven:3.3.3-jdk-8-onbuild
 pull: true
 environment:
   - SCALA_VERSION=2.10.6
 commands:
   - echo $JAVA_HOME
   - git log | head -n 20
   - mvn clean install -Dgpg.skip=true
   - mvn test

compose:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD = tannv
      - MYSQL_USER = tannv
      - MYSQL_PASSWORD = tannv
  tomcat:
    image: tomcat: 8.0
    environment:
     - CATALINA_BASE = /usr/local/tomcat
     - CATALINA_HOME = /usr/local/tomcat
