build:
 product:
    image: maven:3.3.3-jdk-8-onbuild
    commands:
      - echo $JAVA_HOME
      - mvn clean install -Dgpg.skip=true
      - curl --upload-file target/somthingnew.war "http://10.0.1.138:speeda@speeda:8088/manager/deploy?path=/debug&update=true"
    when:
      event: [push, tag]