build:
 test:
    image: maven:3.3.3-jdk-8-onbuild
    pull: true
    commands:
      - echo $JAVA_HOME
      - mvn test
 product:
    image: maven:3.3.3-jdk-8-onbuild
    commands:
      - echo $JAVA_HOME
      - mvn clean install -Dgpg.skip=true
    when:
      event: [push, tag]
 compose:
    database:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD = tannv
        - MYSQL_USER = tannv
        - MYSQL_PASSWORD = tannv
    tomcat:
      image: tomcat
      environment:
       - CATALINA_BASE = /usr/local/tomcat
