build:
 test:
    image: maven:3.3.3-jdk-8-onbuild
    pull: true
    commands:
      - echo $JAVA_HOME
      - mvn test
 product:
    image: maven:3.3.3-jdk-8-onbuild
    commands:
      - echo $JAVA_HOME
      - mvn clean install -Dgpg.skip=true
    when:
      event: [push, tag]
services:
  web:
      image: tomcat:8.5
      ports:
        - "8080:8080"
      volumes:
        - ./target/somthingnew.war:/usr/local/tomcat/webapps/ROOT.war
        - ./target/somthingnew:/usr/local/tomcat/webapps/ROOT

