build:
 image: maven:3.3.3-jdk-8-onbuild
 pull: true
 environment:
   - SCALA_VERSION=2.10.6
 commands:
   - git log | head -n 20
   - mvn clean install -Dgpg.skip=true
   - mvn test

compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword