build:
 image: maven:3.3.3-jdk-8-onbuild
 pull: true
 environment:
  - SCALA_VERSION=2.10.6
 commands:
  - git log | head -n 20
  - mvn clean install -Dgpg.skip=true
  - mvn test

compose:
  database:
   image: mysql:5.7
   restart: always
   stdin_open: true
   environment:
    MYSQL_ROOT_PASSWORD: supersecret
    MYSQL_DATABASE: drone
    MYSQL_USER: drone
    MYSQL_PASSWORD: drone
    volumes:
    - /data/mysql:/var/lib/mysql